apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-app
  labels:
    app: load
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
      - name: load
        image: azii1/loadgenerator-app:latest
        ports:
        - containerPort: 80
