apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadgeneratorapp-app
  template:
    metadata:
      labels:
        app: loadgeneratorapp-app
    spec:
      containers:
      - name: loadgeneratorapp-app
        image: azii1/loadgeneratorapp-app:latest
        ports:
        - containerPort: 80
