apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
      - name: load-container
        image: azii1/loadgeneratorapp-app:latest
        ports:
        - containerPort: 80
