apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    app: loadgenerator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadgenerator-app
  template:
    metadata:
      labels:
        app: loadgenerator-app
    spec:
      containers:
      - name: load
        image: azii1/loadgenerator-app:latest
        ports:
        - containerPort: 80
