apiVersion: v1
kind: Service
metadata:
  name: load-generator-service
spec:
  selector:
    app: loadgeneratorapp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
